# site settings
title: WebID
author: Sam Goto
description:
username: samuelgoto
issues: https://github.com/samuelgoto/WebID/issues/new

# Author
author:
  name:         Sam Goto
  url:          http://sgo.to
  email:        samuelgoto@gmail.com

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# build settings
port: 4000
highlighter: rouge
# markdown: redcarpet
# permalink: pretty

markdown: kramdown

kramdown:
  input: GFM          # this is a support for GitHub Flavored Markdown
  auto_ids: true      # Auto-generate ID's for headings


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# remote_theme: chesterhow/tale

# permalink:    /:year/:month/:day/:title
permalink: pretty

paginate:     7

#  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

paginate_path: "/pages/:num/"

# include: ["_posts"]

safe: true

# Enables .md files to be rendered as HTML pages
# through the default "post" layout.

# Removes .md from the default rendering pipeline
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# This makes all content here be served as "text/html",
# as a fallback, to enable .md files to be interpreted by
# browsers as html files.
# 
# This works locally, but not on github
#   https://github.com/github/pages-gem/issues/415
#
# webrick:
#   headers:
#    Content-Type: "text/html"

collections:
  posts:
    output: true
    # permalink: /posts/:year/:month/:day/:title.html
    # permalink: /:collection/:name
    # redirect_from: pretty

# optional_front_matter:
#  remove_originals: false
